# Generated by Django 5.0.6 on 2024-05-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0002_alter_universitybranch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_school_name', models.CharField(max_length=255)),
                ('primary_school_year_attended', models.CharField(max_length=50)),
                ('primary_school_address', models.CharField(max_length=255)),
                ('secondary_school_name', models.CharField(max_length=255)),
                ('secondary_school_year_attended', models.CharField(max_length=50)),
                ('secondary_school_address', models.CharField(max_length=255)),
                ('veta_name', models.CharField(blank=True, max_length=255, null=True)),
                ('veta_program', models.CharField(blank=True, max_length=255, null=True)),
                ('veta_year_attended', models.CharField(blank=True, max_length=50, null=True)),
                ('veta_address', models.CharField(blank=True, max_length=255, null=True)),
                ('college_name', models.CharField(blank=True, max_length=255, null=True)),
                ('college_program', models.CharField(blank=True, max_length=255, null=True)),
                ('college_year_attended', models.CharField(blank=True, max_length=50, null=True)),
                ('college_address', models.CharField(blank=True, max_length=255, null=True)),
                ('university_name', models.CharField(max_length=255)),
                ('university_course_title', models.CharField(max_length=255)),
                ('university_relevant_course', models.TextField()),
                ('university_graduation_year', models.CharField(max_length=50)),
            ],
        ),
    ]
