# Generated by Django 5.0.6 on 2024-05-31 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0005_educationalbackground_alumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherinfo',
            name='alumni',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
