# Generated by Django 5.0.6 on 2024-05-31 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0006_alter_otherinfo_alumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalbackground',
            name='alumni',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='educational_background', to=settings.AUTH_USER_MODEL),
        ),
    ]
