# Generated by Django 5.0.6 on 2024-05-31 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0007_alter_educationalbackground_alumni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='fix_index',
            new_name='fvi_index',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='parent_phone',
        ),
    ]
