# Generated by Django 5.0.6 on 2024-05-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0008_rename_fix_index_alumni_fvi_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='sex',
            field=models.CharField(max_length=7),
        ),
    ]
