# Generated by Django 5.0.6 on 2024-06-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0009_alter_alumni_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='start_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
