# Generated by Django 5.0.6 on 2024-06-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0010_alter_history_end_year_alter_history_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalbackground',
            name='college_year_attended',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='educationalbackground',
            name='primary_school_year_attended',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='educationalbackground',
            name='secondary_school_year_attended',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='educationalbackground',
            name='university_graduation_year',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='educationalbackground',
            name='veta_year_attended',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
